/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ConexionPool;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author jrblanco
 */
public class SplashScreen extends javax.swing.JFrame implements Runnable{
    
    private Thread hiloThread = null;
    private boolean ejecutar = true;
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        setLocationRelativeTo(null);
        hiloThread = new Thread(this);
        hiloThread.start();
        
        this.lbTexto.setText("Conectando con el servidor SQL " + ConexionPool.getInstancia().getIP());
        
        setVisible(true);
    }
    
    @Override
    public void run(){
        String p = ".";
        int contador = 1;
        try {
            while (this.ejecutar) {     //Bucle para la animación de los puntitos...
                this.lbpuntos.setText(p);
                Thread.sleep(500);
                p = p + " .";
                if (contador==10){
                    p = ".";
                    contador=0;
                }
                contador++;
            }
        } catch (InterruptedException ex) {
             System.out.println("Error en el hilo del SplashScreen");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraProgreso = new javax.swing.JProgressBar();
        lbTexto = new javax.swing.JLabel();
        lbNombreApp = new javax.swing.JLabel();
        lbpuntos = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraProgreso.setToolTipText("");
        BarraProgreso.setName(""); // NOI18N
        jPanel1.add(BarraProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 430, 5));

        lbTexto.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbTexto.setForeground(new java.awt.Color(255, 255, 255));
        lbTexto.setText("text");
        jPanel1.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 310, -1));

        lbNombreApp.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbNombreApp.setForeground(new java.awt.Color(0, 0, 0));
        lbNombreApp.setText("Gestión Java 0.1");
        jPanel1.add(lbNombreApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, -1));

        lbpuntos.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbpuntos.setForeground(new java.awt.Color(255, 255, 255));
        lbpuntos.setText(". . . . . . . . . .");
        jPanel1.add(lbpuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 90, -1));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SplassScreen.png"))); // NOI18N
        imgFondo.setText("jLabel1");
        jPanel1.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.ejecutar = false;
    }//GEN-LAST:event_formWindowClosed

    
//        /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaPrincipal().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgreso;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNombreApp;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbpuntos;
    // End of variables declaration//GEN-END:variables
}
